name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: Setup
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y flex build-essential
        gem install markspec
    - name: Build
      run: make
    - name: Test
      run: markspec
