name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Setup
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y flex build-essential libfl-dev
        gem install markspec
    - name: Build
      run: |
        make all
    - name: Test
      run: markspec
